#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrolojiApp.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UrolojiDB")]
	public partial class UrolojiDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertbTakip(bTakip instance);
    partial void UpdatebTakip(bTakip instance);
    partial void DeletebTakip(bTakip instance);
    partial void InsertbDemografik(bDemografik instance);
    partial void UpdatebDemografik(bDemografik instance);
    partial void DeletebDemografik(bDemografik instance);
    partial void InsertbHastaBilgileri(bHastaBilgileri instance);
    partial void UpdatebHastaBilgileri(bHastaBilgileri instance);
    partial void DeletebHastaBilgileri(bHastaBilgileri instance);
    partial void InsertbOperatif(bOperatif instance);
    partial void UpdatebOperatif(bOperatif instance);
    partial void DeletebOperatif(bOperatif instance);
    partial void InsertbPatoloji(bPatoloji instance);
    partial void UpdatebPatoloji(bPatoloji instance);
    partial void DeletebPatoloji(bPatoloji instance);
    partial void InsertbPosOperatif(bPosOperatif instance);
    partial void UpdatebPosOperatif(bPosOperatif instance);
    partial void DeletebPosOperatif(bPosOperatif instance);
    partial void InsertbOpTuru(bOpTuru instance);
    partial void UpdatebOpTuru(bOpTuru instance);
    partial void DeletebOpTuru(bOpTuru instance);
    #endregion
		
		public UrolojiDbDataContext() : 
				base(global::UrolojiApp.Properties.Settings.Default.UrolojiDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UrolojiDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UrolojiDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UrolojiDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UrolojiDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bTakip> bTakips
		{
			get
			{
				return this.GetTable<bTakip>();
			}
		}
		
		public System.Data.Linq.Table<bDemografik> bDemografiks
		{
			get
			{
				return this.GetTable<bDemografik>();
			}
		}
		
		public System.Data.Linq.Table<bHastaBilgileri> bHastaBilgileris
		{
			get
			{
				return this.GetTable<bHastaBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<bOperatif> bOperatifs
		{
			get
			{
				return this.GetTable<bOperatif>();
			}
		}
		
		public System.Data.Linq.Table<bPatoloji> bPatolojis
		{
			get
			{
				return this.GetTable<bPatoloji>();
			}
		}
		
		public System.Data.Linq.Table<bPosOperatif> bPosOperatifs
		{
			get
			{
				return this.GetTable<bPosOperatif>();
			}
		}
		
		public System.Data.Linq.Table<bOpTuru> bOpTurus
		{
			get
			{
				return this.GetTable<bOpTuru>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bTakip")]
	public partial class bTakip : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _HastaId;
		
		private string _P3AyLokal;
		
		private System.Nullable<decimal> _P3AyKreatin;
		
		private string _P6AyLokal;
		
		private System.Nullable<decimal> _P6AyKreatin;
		
		private string _P12AyLokal;
		
		private System.Nullable<decimal> _P12AyKreatin;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    partial void OnP3AyLokalChanging(string value);
    partial void OnP3AyLokalChanged();
    partial void OnP3AyKreatinChanging(System.Nullable<decimal> value);
    partial void OnP3AyKreatinChanged();
    partial void OnP6AyLokalChanging(string value);
    partial void OnP6AyLokalChanged();
    partial void OnP6AyKreatinChanging(System.Nullable<decimal> value);
    partial void OnP6AyKreatinChanged();
    partial void OnP12AyLokalChanging(string value);
    partial void OnP12AyLokalChanged();
    partial void OnP12AyKreatinChanging(System.Nullable<decimal> value);
    partial void OnP12AyKreatinChanged();
    #endregion
		
		public bTakip()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P3AyLokal", DbType="NVarChar(5)")]
		public string P3AyLokal
		{
			get
			{
				return this._P3AyLokal;
			}
			set
			{
				if ((this._P3AyLokal != value))
				{
					this.OnP3AyLokalChanging(value);
					this.SendPropertyChanging();
					this._P3AyLokal = value;
					this.SendPropertyChanged("P3AyLokal");
					this.OnP3AyLokalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P3AyKreatin", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> P3AyKreatin
		{
			get
			{
				return this._P3AyKreatin;
			}
			set
			{
				if ((this._P3AyKreatin != value))
				{
					this.OnP3AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._P3AyKreatin = value;
					this.SendPropertyChanged("P3AyKreatin");
					this.OnP3AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P6AyLokal", DbType="NVarChar(5)")]
		public string P6AyLokal
		{
			get
			{
				return this._P6AyLokal;
			}
			set
			{
				if ((this._P6AyLokal != value))
				{
					this.OnP6AyLokalChanging(value);
					this.SendPropertyChanging();
					this._P6AyLokal = value;
					this.SendPropertyChanged("P6AyLokal");
					this.OnP6AyLokalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P6AyKreatin", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> P6AyKreatin
		{
			get
			{
				return this._P6AyKreatin;
			}
			set
			{
				if ((this._P6AyKreatin != value))
				{
					this.OnP6AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._P6AyKreatin = value;
					this.SendPropertyChanged("P6AyKreatin");
					this.OnP6AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P12AyLokal", DbType="NVarChar(5)")]
		public string P12AyLokal
		{
			get
			{
				return this._P12AyLokal;
			}
			set
			{
				if ((this._P12AyLokal != value))
				{
					this.OnP12AyLokalChanging(value);
					this.SendPropertyChanging();
					this._P12AyLokal = value;
					this.SendPropertyChanged("P12AyLokal");
					this.OnP12AyLokalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P12AyKreatin", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> P12AyKreatin
		{
			get
			{
				return this._P12AyKreatin;
			}
			set
			{
				if ((this._P12AyKreatin != value))
				{
					this.OnP12AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._P12AyKreatin = value;
					this.SendPropertyChanged("P12AyKreatin");
					this.OnP12AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bTakip", Storage="_bHastaBilgileri", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bTakips.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bTakips.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bDemografik")]
	public partial class bDemografik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _HastaId;
		
		private System.Nullable<int> _Yas;
		
		private System.Nullable<int> _Boy;
		
		private System.Nullable<decimal> _Kilo;
		
		private System.Nullable<decimal> _Bmi;
		
		private System.Nullable<int> _Asa;
		
		private string _Dr;
		
		private string _Cins;
		
		private string _Taraf;
		
		private string _Lokalizasyon;
		
		private string _Boyut;
		
		private string _Ko_Morbit;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    partial void OnYasChanging(System.Nullable<int> value);
    partial void OnYasChanged();
    partial void OnBoyChanging(System.Nullable<int> value);
    partial void OnBoyChanged();
    partial void OnKiloChanging(System.Nullable<decimal> value);
    partial void OnKiloChanged();
    partial void OnBmiChanging(System.Nullable<decimal> value);
    partial void OnBmiChanged();
    partial void OnAsaChanging(System.Nullable<int> value);
    partial void OnAsaChanged();
    partial void OnDrChanging(string value);
    partial void OnDrChanged();
    partial void OnCinsChanging(string value);
    partial void OnCinsChanged();
    partial void OnTarafChanging(string value);
    partial void OnTarafChanged();
    partial void OnLokalizasyonChanging(string value);
    partial void OnLokalizasyonChanged();
    partial void OnBoyutChanging(string value);
    partial void OnBoyutChanged();
    partial void OnKo_MorbitChanging(string value);
    partial void OnKo_MorbitChanged();
    #endregion
		
		public bDemografik()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yas", DbType="Int")]
		public System.Nullable<int> Yas
		{
			get
			{
				return this._Yas;
			}
			set
			{
				if ((this._Yas != value))
				{
					this.OnYasChanging(value);
					this.SendPropertyChanging();
					this._Yas = value;
					this.SendPropertyChanged("Yas");
					this.OnYasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boy", DbType="Int")]
		public System.Nullable<int> Boy
		{
			get
			{
				return this._Boy;
			}
			set
			{
				if ((this._Boy != value))
				{
					this.OnBoyChanging(value);
					this.SendPropertyChanging();
					this._Boy = value;
					this.SendPropertyChanged("Boy");
					this.OnBoyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Kilo
		{
			get
			{
				return this._Kilo;
			}
			set
			{
				if ((this._Kilo != value))
				{
					this.OnKiloChanging(value);
					this.SendPropertyChanging();
					this._Kilo = value;
					this.SendPropertyChanged("Kilo");
					this.OnKiloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bmi", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> Bmi
		{
			get
			{
				return this._Bmi;
			}
			set
			{
				if ((this._Bmi != value))
				{
					this.OnBmiChanging(value);
					this.SendPropertyChanging();
					this._Bmi = value;
					this.SendPropertyChanged("Bmi");
					this.OnBmiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asa", DbType="Int")]
		public System.Nullable<int> Asa
		{
			get
			{
				return this._Asa;
			}
			set
			{
				if ((this._Asa != value))
				{
					this.OnAsaChanging(value);
					this.SendPropertyChanging();
					this._Asa = value;
					this.SendPropertyChanged("Asa");
					this.OnAsaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dr", DbType="NVarChar(200)")]
		public string Dr
		{
			get
			{
				return this._Dr;
			}
			set
			{
				if ((this._Dr != value))
				{
					this.OnDrChanging(value);
					this.SendPropertyChanging();
					this._Dr = value;
					this.SendPropertyChanged("Dr");
					this.OnDrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cins", DbType="NVarChar(2)")]
		public string Cins
		{
			get
			{
				return this._Cins;
			}
			set
			{
				if ((this._Cins != value))
				{
					this.OnCinsChanging(value);
					this.SendPropertyChanging();
					this._Cins = value;
					this.SendPropertyChanged("Cins");
					this.OnCinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taraf", DbType="NVarChar(2)")]
		public string Taraf
		{
			get
			{
				return this._Taraf;
			}
			set
			{
				if ((this._Taraf != value))
				{
					this.OnTarafChanging(value);
					this.SendPropertyChanging();
					this._Taraf = value;
					this.SendPropertyChanged("Taraf");
					this.OnTarafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokalizasyon", DbType="NVarChar(250)")]
		public string Lokalizasyon
		{
			get
			{
				return this._Lokalizasyon;
			}
			set
			{
				if ((this._Lokalizasyon != value))
				{
					this.OnLokalizasyonChanging(value);
					this.SendPropertyChanging();
					this._Lokalizasyon = value;
					this.SendPropertyChanged("Lokalizasyon");
					this.OnLokalizasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="NVarChar(50)")]
		public string Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this.OnBoyutChanging(value);
					this.SendPropertyChanging();
					this._Boyut = value;
					this.SendPropertyChanged("Boyut");
					this.OnBoyutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ko_Morbit", DbType="NVarChar(50)")]
		public string Ko_Morbit
		{
			get
			{
				return this._Ko_Morbit;
			}
			set
			{
				if ((this._Ko_Morbit != value))
				{
					this.OnKo_MorbitChanging(value);
					this.SendPropertyChanging();
					this._Ko_Morbit = value;
					this.SendPropertyChanged("Ko_Morbit");
					this.OnKo_MorbitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bDemografik", Storage="_bHastaBilgileri", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bDemografiks.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bDemografiks.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bHastaBilgileri")]
	public partial class bHastaBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Hadi;
		
		private string _Hsoyadi;
		
		private string _ProtokolNo;
		
		private System.Nullable<System.DateTime> _OpTarihi;
		
		private string _OpTuru;
		
		private System.Nullable<int> _Takip;
		
		private System.Nullable<int> _Anah;
		
		private EntitySet<bTakip> _bTakips;
		
		private EntitySet<bDemografik> _bDemografiks;
		
		private EntitySet<bOperatif> _bOperatifs;
		
		private EntitySet<bPatoloji> _bPatolojis;
		
		private EntitySet<bPosOperatif> _bPosOperatifs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHadiChanging(string value);
    partial void OnHadiChanged();
    partial void OnHsoyadiChanging(string value);
    partial void OnHsoyadiChanged();
    partial void OnProtokolNoChanging(string value);
    partial void OnProtokolNoChanged();
    partial void OnOpTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOpTarihiChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    partial void OnTakipChanging(System.Nullable<int> value);
    partial void OnTakipChanged();
    partial void OnAnahChanging(System.Nullable<int> value);
    partial void OnAnahChanged();
    #endregion
		
		public bHastaBilgileri()
		{
			this._bTakips = new EntitySet<bTakip>(new Action<bTakip>(this.attach_bTakips), new Action<bTakip>(this.detach_bTakips));
			this._bDemografiks = new EntitySet<bDemografik>(new Action<bDemografik>(this.attach_bDemografiks), new Action<bDemografik>(this.detach_bDemografiks));
			this._bOperatifs = new EntitySet<bOperatif>(new Action<bOperatif>(this.attach_bOperatifs), new Action<bOperatif>(this.detach_bOperatifs));
			this._bPatolojis = new EntitySet<bPatoloji>(new Action<bPatoloji>(this.attach_bPatolojis), new Action<bPatoloji>(this.detach_bPatolojis));
			this._bPosOperatifs = new EntitySet<bPosOperatif>(new Action<bPosOperatif>(this.attach_bPosOperatifs), new Action<bPosOperatif>(this.detach_bPosOperatifs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hadi", DbType="NVarChar(50)")]
		public string Hadi
		{
			get
			{
				return this._Hadi;
			}
			set
			{
				if ((this._Hadi != value))
				{
					this.OnHadiChanging(value);
					this.SendPropertyChanging();
					this._Hadi = value;
					this.SendPropertyChanged("Hadi");
					this.OnHadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hsoyadi", DbType="NVarChar(50)")]
		public string Hsoyadi
		{
			get
			{
				return this._Hsoyadi;
			}
			set
			{
				if ((this._Hsoyadi != value))
				{
					this.OnHsoyadiChanging(value);
					this.SendPropertyChanging();
					this._Hsoyadi = value;
					this.SendPropertyChanged("Hsoyadi");
					this.OnHsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProtokolNo", DbType="NVarChar(50)")]
		public string ProtokolNo
		{
			get
			{
				return this._ProtokolNo;
			}
			set
			{
				if ((this._ProtokolNo != value))
				{
					this.OnProtokolNoChanging(value);
					this.SendPropertyChanging();
					this._ProtokolNo = value;
					this.SendPropertyChanged("ProtokolNo");
					this.OnProtokolNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> OpTarihi
		{
			get
			{
				return this._OpTarihi;
			}
			set
			{
				if ((this._OpTarihi != value))
				{
					this.OnOpTarihiChanging(value);
					this.SendPropertyChanging();
					this._OpTarihi = value;
					this.SendPropertyChanged("OpTarihi");
					this.OnOpTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(400)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="Int")]
		public System.Nullable<int> Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anah", DbType="Int")]
		public System.Nullable<int> Anah
		{
			get
			{
				return this._Anah;
			}
			set
			{
				if ((this._Anah != value))
				{
					this.OnAnahChanging(value);
					this.SendPropertyChanging();
					this._Anah = value;
					this.SendPropertyChanged("Anah");
					this.OnAnahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bTakip", Storage="_bTakips", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<bTakip> bTakips
		{
			get
			{
				return this._bTakips;
			}
			set
			{
				this._bTakips.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bDemografik", Storage="_bDemografiks", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<bDemografik> bDemografiks
		{
			get
			{
				return this._bDemografiks;
			}
			set
			{
				this._bDemografiks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bOperatif", Storage="_bOperatifs", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<bOperatif> bOperatifs
		{
			get
			{
				return this._bOperatifs;
			}
			set
			{
				this._bOperatifs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bPatoloji", Storage="_bPatolojis", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<bPatoloji> bPatolojis
		{
			get
			{
				return this._bPatolojis;
			}
			set
			{
				this._bPatolojis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bPosOperatif", Storage="_bPosOperatifs", ThisKey="Id", OtherKey="HastaId")]
		public EntitySet<bPosOperatif> bPosOperatifs
		{
			get
			{
				return this._bPosOperatifs;
			}
			set
			{
				this._bPosOperatifs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bTakips(bTakip entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bTakips(bTakip entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
		
		private void attach_bDemografiks(bDemografik entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bDemografiks(bDemografik entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
		
		private void attach_bOperatifs(bOperatif entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bOperatifs(bOperatif entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
		
		private void attach_bPatolojis(bPatoloji entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bPatolojis(bPatoloji entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
		
		private void attach_bPosOperatifs(bPosOperatif entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = this;
		}
		
		private void detach_bPosOperatifs(bPosOperatif entity)
		{
			this.SendPropertyChanging();
			entity.bHastaBilgileri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bOperatif")]
	public partial class bOperatif : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _HastaId;
		
		private string _PksAciklamasi;
		
		private string _Sikayet;
		
		private string _CoOperasyon;
		
		private System.Nullable<int> _Iskemi;
		
		private System.Nullable<int> _PortSayisi;
		
		private string _YardimYnt;
		
		private System.Nullable<int> _Sure;
		
		private string _Dren;
		
		private System.Nullable<int> _Kanama;
		
		private System.Nullable<int> _Piyes;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    partial void OnPksAciklamasiChanging(string value);
    partial void OnPksAciklamasiChanged();
    partial void OnSikayetChanging(string value);
    partial void OnSikayetChanged();
    partial void OnCoOperasyonChanging(string value);
    partial void OnCoOperasyonChanged();
    partial void OnIskemiChanging(System.Nullable<int> value);
    partial void OnIskemiChanged();
    partial void OnPortSayisiChanging(System.Nullable<int> value);
    partial void OnPortSayisiChanged();
    partial void OnYardimYntChanging(string value);
    partial void OnYardimYntChanged();
    partial void OnSureChanging(System.Nullable<int> value);
    partial void OnSureChanged();
    partial void OnDrenChanging(string value);
    partial void OnDrenChanged();
    partial void OnKanamaChanging(System.Nullable<int> value);
    partial void OnKanamaChanged();
    partial void OnPiyesChanging(System.Nullable<int> value);
    partial void OnPiyesChanged();
    #endregion
		
		public bOperatif()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PksAciklamasi", DbType="NVarChar(2)")]
		public string PksAciklamasi
		{
			get
			{
				return this._PksAciklamasi;
			}
			set
			{
				if ((this._PksAciklamasi != value))
				{
					this.OnPksAciklamasiChanging(value);
					this.SendPropertyChanging();
					this._PksAciklamasi = value;
					this.SendPropertyChanged("PksAciklamasi");
					this.OnPksAciklamasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sikayet", DbType="NVarChar(50)")]
		public string Sikayet
		{
			get
			{
				return this._Sikayet;
			}
			set
			{
				if ((this._Sikayet != value))
				{
					this.OnSikayetChanging(value);
					this.SendPropertyChanging();
					this._Sikayet = value;
					this.SendPropertyChanged("Sikayet");
					this.OnSikayetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoOperasyon", DbType="NVarChar(150)")]
		public string CoOperasyon
		{
			get
			{
				return this._CoOperasyon;
			}
			set
			{
				if ((this._CoOperasyon != value))
				{
					this.OnCoOperasyonChanging(value);
					this.SendPropertyChanging();
					this._CoOperasyon = value;
					this.SendPropertyChanged("CoOperasyon");
					this.OnCoOperasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iskemi", DbType="Int")]
		public System.Nullable<int> Iskemi
		{
			get
			{
				return this._Iskemi;
			}
			set
			{
				if ((this._Iskemi != value))
				{
					this.OnIskemiChanging(value);
					this.SendPropertyChanging();
					this._Iskemi = value;
					this.SendPropertyChanged("Iskemi");
					this.OnIskemiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortSayisi", DbType="Int")]
		public System.Nullable<int> PortSayisi
		{
			get
			{
				return this._PortSayisi;
			}
			set
			{
				if ((this._PortSayisi != value))
				{
					this.OnPortSayisiChanging(value);
					this.SendPropertyChanging();
					this._PortSayisi = value;
					this.SendPropertyChanged("PortSayisi");
					this.OnPortSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YardimYnt", DbType="NVarChar(50)")]
		public string YardimYnt
		{
			get
			{
				return this._YardimYnt;
			}
			set
			{
				if ((this._YardimYnt != value))
				{
					this.OnYardimYntChanging(value);
					this.SendPropertyChanging();
					this._YardimYnt = value;
					this.SendPropertyChanged("YardimYnt");
					this.OnYardimYntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int")]
		public System.Nullable<int> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="NVarChar(50)")]
		public string Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kanama", DbType="Int")]
		public System.Nullable<int> Kanama
		{
			get
			{
				return this._Kanama;
			}
			set
			{
				if ((this._Kanama != value))
				{
					this.OnKanamaChanging(value);
					this.SendPropertyChanging();
					this._Kanama = value;
					this.SendPropertyChanged("Kanama");
					this.OnKanamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piyes", DbType="Int")]
		public System.Nullable<int> Piyes
		{
			get
			{
				return this._Piyes;
			}
			set
			{
				if ((this._Piyes != value))
				{
					this.OnPiyesChanging(value);
					this.SendPropertyChanging();
					this._Piyes = value;
					this.SendPropertyChanged("Piyes");
					this.OnPiyesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bOperatif", Storage="_bHastaBilgileri", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bOperatifs.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bOperatifs.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bPatoloji")]
	public partial class bPatoloji : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _HastaId;
		
		private string _Patoloji;
		
		private string _AltGrup;
		
		private string _FuhrmanGrade;
		
		private string _PatolojikEvre;
		
		private string _CerrahiSinir;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    partial void OnPatolojiChanging(string value);
    partial void OnPatolojiChanged();
    partial void OnAltGrupChanging(string value);
    partial void OnAltGrupChanged();
    partial void OnFuhrmanGradeChanging(string value);
    partial void OnFuhrmanGradeChanged();
    partial void OnPatolojikEvreChanging(string value);
    partial void OnPatolojikEvreChanged();
    partial void OnCerrahiSinirChanging(string value);
    partial void OnCerrahiSinirChanged();
    #endregion
		
		public bPatoloji()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NVarChar(50)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this.OnPatolojiChanging(value);
					this.SendPropertyChanging();
					this._Patoloji = value;
					this.SendPropertyChanged("Patoloji");
					this.OnPatolojiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGrup", DbType="NVarChar(50)")]
		public string AltGrup
		{
			get
			{
				return this._AltGrup;
			}
			set
			{
				if ((this._AltGrup != value))
				{
					this.OnAltGrupChanging(value);
					this.SendPropertyChanging();
					this._AltGrup = value;
					this.SendPropertyChanged("AltGrup");
					this.OnAltGrupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuhrmanGrade", DbType="NVarChar(30)")]
		public string FuhrmanGrade
		{
			get
			{
				return this._FuhrmanGrade;
			}
			set
			{
				if ((this._FuhrmanGrade != value))
				{
					this.OnFuhrmanGradeChanging(value);
					this.SendPropertyChanging();
					this._FuhrmanGrade = value;
					this.SendPropertyChanged("FuhrmanGrade");
					this.OnFuhrmanGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatolojikEvre", DbType="NVarChar(10)")]
		public string PatolojikEvre
		{
			get
			{
				return this._PatolojikEvre;
			}
			set
			{
				if ((this._PatolojikEvre != value))
				{
					this.OnPatolojikEvreChanging(value);
					this.SendPropertyChanging();
					this._PatolojikEvre = value;
					this.SendPropertyChanged("PatolojikEvre");
					this.OnPatolojikEvreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CerrahiSinir", DbType="NVarChar(10)")]
		public string CerrahiSinir
		{
			get
			{
				return this._CerrahiSinir;
			}
			set
			{
				if ((this._CerrahiSinir != value))
				{
					this.OnCerrahiSinirChanging(value);
					this.SendPropertyChanging();
					this._CerrahiSinir = value;
					this.SendPropertyChanged("CerrahiSinir");
					this.OnCerrahiSinirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bPatoloji", Storage="_bHastaBilgileri", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bPatolojis.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bPatolojis.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bPosOperatif")]
	public partial class bPosOperatif : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _HastaId;
		
		private string _Pek;
		
		private string _PostopAnaliz;
		
		private string _Sonda;
		
		private System.Nullable<int> _HospSuresi;
		
		private System.Nullable<decimal> _PropKreatin;
		
		private System.Nullable<decimal> _PostOpKreatin;
		
		private System.Nullable<decimal> _PreOpHct;
		
		private System.Nullable<decimal> _PostOpHct;
		
		private System.Nullable<decimal> _ProOpHb;
		
		private System.Nullable<decimal> _PostOpHb;
		
		private string _Takip;
		
		private string _Tel;
		
		private string _PostOpGKomp;
		
		private string _KompKlavien;
		
		private EntityRef<bHastaBilgileri> _bHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHastaIdChanging(System.Nullable<int> value);
    partial void OnHastaIdChanged();
    partial void OnPekChanging(string value);
    partial void OnPekChanged();
    partial void OnPostopAnalizChanging(string value);
    partial void OnPostopAnalizChanged();
    partial void OnSondaChanging(string value);
    partial void OnSondaChanged();
    partial void OnHospSuresiChanging(System.Nullable<int> value);
    partial void OnHospSuresiChanged();
    partial void OnPropKreatinChanging(System.Nullable<decimal> value);
    partial void OnPropKreatinChanged();
    partial void OnPostOpKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostOpKreatinChanged();
    partial void OnPreOpHctChanging(System.Nullable<decimal> value);
    partial void OnPreOpHctChanged();
    partial void OnPostOpHctChanging(System.Nullable<decimal> value);
    partial void OnPostOpHctChanged();
    partial void OnProOpHbChanging(System.Nullable<decimal> value);
    partial void OnProOpHbChanged();
    partial void OnPostOpHbChanging(System.Nullable<decimal> value);
    partial void OnPostOpHbChanged();
    partial void OnTakipChanging(string value);
    partial void OnTakipChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnPostOpGKompChanging(string value);
    partial void OnPostOpGKompChanged();
    partial void OnKompKlavienChanging(string value);
    partial void OnKompKlavienChanged();
    #endregion
		
		public bPosOperatif()
		{
			this._bHastaBilgileri = default(EntityRef<bHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaId", DbType="Int")]
		public System.Nullable<int> HastaId
		{
			get
			{
				return this._HastaId;
			}
			set
			{
				if ((this._HastaId != value))
				{
					if (this._bHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIdChanging(value);
					this.SendPropertyChanging();
					this._HastaId = value;
					this.SendPropertyChanged("HastaId");
					this.OnHastaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pek", DbType="NVarChar(50)")]
		public string Pek
		{
			get
			{
				return this._Pek;
			}
			set
			{
				if ((this._Pek != value))
				{
					this.OnPekChanging(value);
					this.SendPropertyChanging();
					this._Pek = value;
					this.SendPropertyChanged("Pek");
					this.OnPekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopAnaliz", DbType="NVarChar(50)")]
		public string PostopAnaliz
		{
			get
			{
				return this._PostopAnaliz;
			}
			set
			{
				if ((this._PostopAnaliz != value))
				{
					this.OnPostopAnalizChanging(value);
					this.SendPropertyChanging();
					this._PostopAnaliz = value;
					this.SendPropertyChanged("PostopAnaliz");
					this.OnPostopAnalizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonda", DbType="NVarChar(50)")]
		public string Sonda
		{
			get
			{
				return this._Sonda;
			}
			set
			{
				if ((this._Sonda != value))
				{
					this.OnSondaChanging(value);
					this.SendPropertyChanging();
					this._Sonda = value;
					this.SendPropertyChanged("Sonda");
					this.OnSondaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospSuresi", DbType="Int")]
		public System.Nullable<int> HospSuresi
		{
			get
			{
				return this._HospSuresi;
			}
			set
			{
				if ((this._HospSuresi != value))
				{
					this.OnHospSuresiChanging(value);
					this.SendPropertyChanging();
					this._HospSuresi = value;
					this.SendPropertyChanged("HospSuresi");
					this.OnHospSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PropKreatin
		{
			get
			{
				return this._PropKreatin;
			}
			set
			{
				if ((this._PropKreatin != value))
				{
					this.OnPropKreatinChanging(value);
					this.SendPropertyChanging();
					this._PropKreatin = value;
					this.SendPropertyChanged("PropKreatin");
					this.OnPropKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpKreatin", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PostOpKreatin
		{
			get
			{
				return this._PostOpKreatin;
			}
			set
			{
				if ((this._PostOpKreatin != value))
				{
					this.OnPostOpKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostOpKreatin = value;
					this.SendPropertyChanged("PostOpKreatin");
					this.OnPostOpKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreOpHct", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PreOpHct
		{
			get
			{
				return this._PreOpHct;
			}
			set
			{
				if ((this._PreOpHct != value))
				{
					this.OnPreOpHctChanging(value);
					this.SendPropertyChanging();
					this._PreOpHct = value;
					this.SendPropertyChanged("PreOpHct");
					this.OnPreOpHctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpHct", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PostOpHct
		{
			get
			{
				return this._PostOpHct;
			}
			set
			{
				if ((this._PostOpHct != value))
				{
					this.OnPostOpHctChanging(value);
					this.SendPropertyChanging();
					this._PostOpHct = value;
					this.SendPropertyChanged("PostOpHct");
					this.OnPostOpHctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProOpHb", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> ProOpHb
		{
			get
			{
				return this._ProOpHb;
			}
			set
			{
				if ((this._ProOpHb != value))
				{
					this.OnProOpHbChanging(value);
					this.SendPropertyChanging();
					this._ProOpHb = value;
					this.SendPropertyChanged("ProOpHb");
					this.OnProOpHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpHb", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PostOpHb
		{
			get
			{
				return this._PostOpHb;
			}
			set
			{
				if ((this._PostOpHb != value))
				{
					this.OnPostOpHbChanging(value);
					this.SendPropertyChanging();
					this._PostOpHb = value;
					this.SendPropertyChanged("PostOpHb");
					this.OnPostOpHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="NVarChar(175)")]
		public string Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(20)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostOpGKomp", DbType="NVarChar(100)")]
		public string PostOpGKomp
		{
			get
			{
				return this._PostOpGKomp;
			}
			set
			{
				if ((this._PostOpGKomp != value))
				{
					this.OnPostOpGKompChanging(value);
					this.SendPropertyChanging();
					this._PostOpGKomp = value;
					this.SendPropertyChanged("PostOpGKomp");
					this.OnPostOpGKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KompKlavien", DbType="NVarChar(5)")]
		public string KompKlavien
		{
			get
			{
				return this._KompKlavien;
			}
			set
			{
				if ((this._KompKlavien != value))
				{
					this.OnKompKlavienChanging(value);
					this.SendPropertyChanging();
					this._KompKlavien = value;
					this.SendPropertyChanged("KompKlavien");
					this.OnKompKlavienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bHastaBilgileri_bPosOperatif", Storage="_bHastaBilgileri", ThisKey="HastaId", OtherKey="Id", IsForeignKey=true)]
		public bHastaBilgileri bHastaBilgileri
		{
			get
			{
				return this._bHastaBilgileri.Entity;
			}
			set
			{
				bHastaBilgileri previousValue = this._bHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._bHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bHastaBilgileri.Entity = null;
						previousValue.bPosOperatifs.Remove(this);
					}
					this._bHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.bPosOperatifs.Add(this);
						this._HastaId = value.Id;
					}
					else
					{
						this._HastaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("bHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bOpTuru")]
	public partial class bOpTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _OpName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnOpNameChanging(string value);
    partial void OnOpNameChanged();
    #endregion
		
		public bOpTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpName", DbType="NVarChar(50)")]
		public string OpName
		{
			get
			{
				return this._OpName;
			}
			set
			{
				if ((this._OpName != value))
				{
					this.OnOpNameChanging(value);
					this.SendPropertyChanging();
					this._OpName = value;
					this.SendPropertyChanged("OpName");
					this.OnOpNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
